# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/juno-adx-client',
                'doc_host': 'https://equinor.github.io',
                'git_url': 'https://github.com/equinor/juno-adx-client',
                'lib_path': 'juno_adx_client'},
  'syms': { 'juno_adx_client.core': { 'juno_adx_client.core.ADXClient': ('core.html#adxclient', 'juno_adx_client/core.py'),
                                      'juno_adx_client.core.ADXClient.__init__': ( 'core.html#adxclient.__init__',
                                                                                   'juno_adx_client/core.py'),
                                      'juno_adx_client.core.ADXClient._create_client': ( 'core.html#adxclient._create_client',
                                                                                         'juno_adx_client/core.py'),
                                      'juno_adx_client.core.ADXClient._create_credential': ( 'core.html#adxclient._create_credential',
                                                                                             'juno_adx_client/core.py'),
                                      'juno_adx_client.core.ADXClient.perform_query': ( 'core.html#adxclient.perform_query',
                                                                                        'juno_adx_client/core.py'),
                                      'juno_adx_client.core.ADXClient.set_interactive_login': ( 'core.html#adxclient.set_interactive_login',
                                                                                                'juno_adx_client/core.py')}}}
